<a href="https://colab.research.google.com/github/kollirajani/vrsec-pytorch/blob/main/VRSEC_tourch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
8+8

16

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
#Create a model class that inherits nn.module
class Model(nn.modu):
#in put layer ( 4 fetures of the flower) --> hiddent layer1 ( number nurons) ---out put layer

def __init__(self, in_features = 4, h1=8, h2=9, out_features=3)
self.fc1 = nn.Linear(in_features=, h1)
sefl.fc2 = nn.Linear(h1, h2)
self.out = nn.Linear(h2, out_features)

def forward(self, x):
  x = F.relu()


In [ ]:
!pip list


Package                            Version
---------------------------------- -------------------
absl-py                            1.4.0
accelerate                         1.3.0
aiohappyeyeballs                   2.4.6
aiohttp                            3.11.12
aiosignal                          1.3.2
alabaster                          1.0.0
albucore                           0.0.23
albumentations                     2.0.4
ale-py                             0.10.1
altair                             5.5.0
annotated-types                    0.7.0
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.6.0
arviz                              0.20.0
astropy                            7.0.1
astropy-iers-data                  0.2025.2.10.0.33.26
astunparse                         1.6.3
atpublic                           4.1.0
attrs                              25.1.0
audioread          

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.05436749, 0.05274304, 0.23450277, 0.47764859],
       [0.04745883, 0.48530186, 0.98017518, 0.49615221],
       [0.57078191, 0.36285065, 0.02218672, 0.5854139 ]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
import torch
tensor_2d = torch.randn(5,5)
tensor_2d

tensor([[-0.1917,  0.4434,  0.0316,  1.3289, -0.1599],
        [-0.2520,  0.8536,  0.2693,  0.8112,  0.0054],
        [-0.1368, -1.6784, -2.4474, -0.0700,  2.6824],
        [ 1.6571, -1.4276,  0.2331,  0.3494, -1.1822],
        [-0.9104,  1.3213,  1.0477,  0.4901,  0.6233]])

In [ ]:
tensor_3d = torch.zeros(5,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
tensor_3d.dtype


torch.float32

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0544, 0.0527, 0.2345, 0.4776],
        [0.0475, 0.4853, 0.9802, 0.4962],
        [0.5708, 0.3629, 0.0222, 0.5854]], dtype=torch.float64)

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
#addtion
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
#addtion function
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
#sub
tensor_b - tensor_a
#sub function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
#mul
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
#mat function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
#division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
#division function
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
#reminder
tensor_b%tensor_a

tensor([0, 0, 1, 0])

In [ ]:
#reminder function
torch.remainder(tensor_b,tensor_a)

NameError: name 'tensor_remainder' is not defined

In [ ]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])